# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
      - id: black
        args: ["--check"]
  - repo: https://github.com/pycqa/isort
    rev: 5.10.1
    hooks:
      - id: isort
        args: ["--check"]
  - repo: local
    hooks:
      - id: pytest
        name: pytest
        entry: pytest
        language: system
        pass_filenames: false
        always_run: true
  - repo: local
    hooks:
      - id: mypy
        name: mypy
        entry: mypy
        language: system
        always_run: true
  - repo: local
    hooks:
      - id: pyright
        name: pyright
        entry: pyright
        language: system
        pass_filenames: false
        always_run: true
  - repo: local
    hooks:
      - id: slotscheck
        name: slotscheck
        entry: slotscheck nextcore/
        language: system
        pass_filenames: false
        always_run: true
